# Site settings
title: Viraj Parimi
description: Personal Site
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/site" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Viraj Parimi
user_title: Student
email: parimi15068@iiitd.ac.in
github_username:  viraj96

# Google-analytics
google-analytics:
  id: "UA-110955894-1"

exclude: ['package.json', 'src' , 'node_modules']